# Generated by Django 5.1.2 on 2024-10-24 06:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_image', models.URLField(max_length=300, verbose_name='Product URL')),
                ('product_description', models.CharField(max_length=300, verbose_name='Product Description')),
                ('slug_field', models.SlugField(max_length=100, unique=True, verbose_name='slug_field')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_serial_Number', models.CharField(max_length=50, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Product Price')),
                ('product_quantity', models.PositiveIntegerField(default=0, verbose_name='Product Quantity')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Product Rating')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date_ordered', models.DateField(default=datetime.datetime(2024, 10, 24, 9, 52, 8, 210319))),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.BooleanField(default=False, verbose_name='Status, Whether Delivered or Not')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
