# Generated by Django 5.1.2 on 2024-10-24 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(default=datetime.datetime(2024, 10, 24, 6, 53, 54, 148322, tzinfo=datetime.timezone.utc)),
        ),
    ]
