# Generated by Django 5.1.2 on 2024-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_field',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug_field'),
        ),
    ]
