# Generated by Django 5.1.2 on 2024-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug_field'),
        ),
    ]
