# Generated by Django 5.1.2 on 2024-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.ImageField(null=True, upload_to='product_images/', verbose_name='Product Image'),
        ),
    ]
